language: go
go:
  - 1.6.x
  - 1.7.x
env:
  - GOARCH=amd64
  - GOARCH=386
  - TEST_RACE=true
  - TEST_RACE=false
sudo: false
script:
  - curl -s https://raw.githubusercontent.com/pote/gpm/v1.4.0/bin/gpm > gpm
  - chmod +x gpm
  - ./gpm install
  - ./test.sh
notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)