language: go
go:
  - 1.9.x
  - 1.10.x
env:
  - GOARCH=amd64 TEST_RACE=false
  - GOARCH=amd64 TEST_RACE=true
  - GOARCH=386 TEST_RACE=false
  - GOARCH=386 TEST_RACE=true
sudo: false
script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - travis_wait ./test.sh
notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)